---
- name: "Zabbix smart mon: Install smartmontools"
  package:
    name: "{{smartmontools_packages}}"
    state: latest

- name: "Zabbix smart mon: Copy sudoers file"
  template:
    src: sudoers_zabbix_smartctl
    dest: /etc/sudoers.d/sudoers_zabbix_smartctl
    validate: "visudo -cf %s"
    mode: 0440

- name: "Zabbix smart mon: Copy agent config"
  template:
    src: zabbix_smartctl.conf
    dest: /etc/zabbix/zabbix_agentd.d/zabbix_smartctl.conf

- name: "Zabbix smart mon: Create scripts directory"
  file:
    path: /etc/zabbix/scripts
    state: directory

- name: "Zabbix smart mon: Copy script"
  template:
    src: smartctl-disks-discovery.pl
    dest: /etc/zabbix/scripts/smartctl-disks-discovery.pl

- name: "Zabbix smart mon: Ensure script is executable"
  file: dest=/etc/zabbix/scripts/smartctl-disks-discovery.pl mode=a+x

- name: "Zabbix smart mon: Restart zabbix-agent via systemd"
  systemd:
    name: zabbix-agent
    state: restarted
